#!/bin/sh
# Build SD card image

BOARD_ID="${1}" # For example "r1500"
CHIP_ID="${2}" # For example "rk3399"
DEFCONFIG="${3}" # For example "nanopi-r4s-rk3399_defconfig"
TUPLE="${4}" # For example "arm-linux-gnueabihf"

set -ex

RKBIN_GIT_REV_DEFAULT="b4558da0860ca48bf1a571dd33ccba580b9abe23"
RKBIN_GIT_URL_DEFAULT="https://github.com/chris00001/rockchip-linux-tpe-r1500.git"


#RKBIN_GIT_URL_DEFAULT="https://github.com/rockchip-linux/rkbin.git"
#RKBIN_GIT_REV_DEFAULT="0f8ac860f0479da56a1decae207ddc99e289f2e2"

if [ ! -z "${RKBIN_GIT_REV}" ]
then
    git clone --depth 1 \
              --reference-if-able "${WORKDIR}/rkbin" \
              "${RKBIN_GIT_URL:-${RKBIN_GIT_URL_DEFAULT}}" rkbin
else
    git clone --reference-if-able "${WORKDIR}/rkbin" \
              "${RKBIN_GIT_URL:-${RKBIN_GIT_URL_DEFAULT}}" rkbin
    git -C rkbin checkout "${RKBIN_GIT_REV_DEFAULT}"
fi

case "${CHIP_ID}" in
rk3328|rk3368|rk3399)
    build-atf "${CHIP_ID}" "${TUPLE}"
    export BL31="$(pwd)/arm-trusted-firmware/build/${CHIP_ID}/debug/bl31/bl31.elf"
    ;;
*)
    ;;
esac

build-u_boot "${DEFCONFIG}" "${TUPLE}"

# Copy U-Boot to 64 sectors from start
dd if=u-boot/u-boot-rockchip.bin of=tmp.img seek=64 conv=notrunc
